package:
  name: dappled-core
  version: "0.1.1"

source:
  path: ../

build:
  entry_points:
    - dappled-run = dappled_core.web:main

requirements:
  build:
    - python

  run:
    - python
    - notebook
    - ruamel.yaml
    - jupyter_dashboards
    - psutil
    - netifaces
    - requests

test:
  imports:

  commands:

about:
  home: https://github.com/lhon/dappled-core
  license: Apache License v2.0
  summary: Supporting tool for the dappled project
  license_family: Apache

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
